name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login
        uses: azure/login@v1.4.0
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          
      - name: Run a one-line script
        uses: azure/CLI@v1
        with:
          inlineScript: az ad app credential reset --id $targetID --display-name test --append
          targetID: ${{ secrets.TARGETID }}
