name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        uses: azure/CLI@v1
        with:
          inlineScript: az ad app credential reset --id ${env.targetID} --display-name test --append
          targetID: ${secrets.TARGETID}
