name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/CLI@v1
      - name: Run a one-line script
        with:
          inlineScript: az ad app credential reset --id ${secrets.targetId} --display-name test --append
